### ISSUE TITLE
I would like to play, pause and seek bar

### ISSUE THREAD

**Issue by vbastianpc** [pixlwave/pixlwave.github.io#1]
This app is simply and awesome. Since VLC doesn't support Syphon, I want to use Vidue Stack. Could you add play, pause and seek bar buttons to control media input?

If there was the source code, maybe I would study it and add that functionality.

**Comment by pixlwave** [comment]
Thanks for the kind words. I can't say this is something I'll be able to add in the near future, but could you provide a bit more insight into what you're looking for? E.g. if you have many outputs patched, are you looking to pause a whole cue at once, or individual outputs?

**Comment by vbastianpc** [comment]
I love how easy it is to add media files with drag and drop. Also how elegant it is to add a transition, add Ken Burns to photos, audio and loop to videos ...

But at the moment it is not useful for my requirements. I would like it to have this two features (with the first I can survive):

- I need to pause videos on the fly. I can't always know in advance where I will have to pause the video. Pause / play the whole cue is fine for me.

- Instead of transcoding my videos by cutting them into seek accurate clips (many long videos split into short clips, intense cpu load), I make a playlist. Each track must have a title, start-time and stop-time. I think a playlist-of-one-video would make sense, respecting the logic of your program. So when you drag and drop playlist file (.xspf or .m3u), a video would be added to the cue with specified start-time and end-time.

Example .xspf playlist
```
<?xml version="1.0" encoding="UTF-8"?>
<playlist xmlns="http://xspf.org/ns/0/" xmlns:vlc="http://www.videolan.org/vlc/playlist/ns/0/" version="1">
	<title>Playlist</title>
	<trackList>
		<track><location>file:///path/to/file/video.mp4</location>
		<title>Video Title</title>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:option>start-time=645.178512</vlc:option>
				<vlc:option>stop-time=675.488822</vlc:option>
			</extension>
		</track>
	</trackList>
</playlist>
```

Example .m3u playlist

```
#EXTM3U
#EXTINF:0, Video Title
#EXTVLCOPT:start-time=645.178512
#EXTVLCOPT:stop-time=675.488822
file:///path/to/file/video.mp4
```

With these two features, I will be happy.

I can imagine other features (not so important), like
- Time elapsed with seek bar.
- For videos that have chapter markers, it would be great to navigate between them.
- Add optional per cue 'continue when shorter video ends', 'continue when longer videos ends'
- Add Facetime Camera as if it were a multimedia file.

I understand that this project is 5 years old and that there is no time to work on it. Maybe it would be possible if there were 8 days a week :) Thank you for your attention.

**Comment by pixlwave** [comment]
Thanks for the extra info. Play/pause does sound like plausible addition at some stage. I've noted everything down on my system 🙂

Will close this bug, thanks for contacting me.

**Comment by vbastianpc** [comment]
I really appreciate your time and disposition. Thanks
